name: Trigger Repo2 Workflow

on:
  push:
    branches:
      - main  # or specify your desired branch

jobs:
  trigger_repo2:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in cicd
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.SECRET_TOKEN }}
          repository: hanzla-spec/cicd # Replace with the actual Repo2 details
          event-type: trigger-build-deploy # Custom event name
          client-payload: '{"branch": "${{ github.ref }}", "commit": "${{ github.sha }}"}'
