# .github/workflows/trigger-repo2.yml

name: Trigger Repo2 Workflow

on:
  push:
    branches:
      - main  # Adjust this to the branch you want to trigger the workflow on

jobs:
  trigger-repo2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout api
        uses: actions/checkout@v3

      - name: Checkout cicd
        uses: actions/checkout@v3
        with:
          repository: hanzla-spec/cicd

      - name: check ls..
        run: ./start.sh
