name: Push Event Workflow

on:
  push:
    branches:
      - poc

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Get Commit ID and Message
        id: get_commit_info
        run: |
          echo "Author Name: ${{ github.event.head_commit.author.name }}"
          echo "Author Email: ${{ github.event.head_commit.author.email }}"
          echo "Commit Hash: ${{ github.event.after }}"
          echo "Date: ${{ github.event.head_commit.timestamp }}"
          echo "Commit Message: ${{ github.event.head_commit.message }}"

      - name: Trigger Workflow Dispatch
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/dispatch.yml/dispatches \
          -d '{"ref": "main", "inputs": {"trigger_info": "Commit ID: ${{ github.event.after }} \n Change for: ${{ github.event.head_commit.message }}\n Pushed by: ${{ github.event.head_commit.author.name }}  "}}'
