name: Push Event Workflow

on:
  push:
    branches:
      - main
      - poc

jobs:
  trigger_dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit ID
        id: get_commit_id
        run: |
          echo "COMMIT_ID=$(echo $GITHUB_SHA)" >> $GITHUB_ENV


      - name: Trigger Workflow Dispatch
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/dispatch.yml/dispatches \
          -d '{"ref": "poc", "inputs": {"commit_id": "${{ env.COMMIT_ID }}"}}'
